import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Benefit from '../components/Benefit'
import Blog from '../components/Blog'
import CarouselSection from '../components/CarouselSection'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Banner/>
      <Benefit/>
      <Blog/>
      <CarouselSection/>
    </div>
  )
}
